In [2]:
import numpy as np

In [5]:
def parent(n, seed = None):
    rng = np.random.default_rng(seed)
    chars = 'abcdefghjkl'
    for i in range(n):
        yield from child(chars[i], rng)

In [11]:
def child(c, rng):
    n = rng.integers(2,5)
    for i in range(n):
        yield f'{i}/{n}: {c}'

In [12]:
gen = parent(5)

In [13]:
for x in gen:
    print(x)

0/2: a
1/2: a
0/4: b
1/4: b
2/4: b
3/4: b
0/3: c
1/3: c
2/3: c
0/3: d
1/3: d
2/3: d
0/4: e
1/4: e
2/4: e
3/4: e


In [35]:
def evaluate(arg, context):
    if callable(arg) and arg.context==context:
        return arg()
    return arg

In [36]:
def pulse(output, duration):
    for i in range(duration):
        yield output

In [37]:
def sequence(**kwargs):
    defaults = dict(on_pulse = (1,0),
                    off_pulse = (0,0),
                    final_pulse = (0,1),
                    on_duration = 5,
                    off_duration = 3,
                    final_duration = 5,
                    n_pulses = 3)
    args = {**defaults, **kwargs}
    for k,v in args.items():
        args[k] = evaluate(v, 'sequence')
    for i in range(args['n_pulses']-1):
        yield from pulse(args['on_pulse'], args['on_duration'])
        yield from pulse(args['off_pulse'], args['off_duration'])
    yield from pulse(args['final_pulse'], args['final_duration'])

In [38]:
seq = sequence()
for x in seq:
    print(x)

(1, 0)
(1, 0)
(1, 0)
(1, 0)
(1, 0)
(0, 0)
(0, 0)
(0, 0)
(1, 0)
(1, 0)
(1, 0)
(1, 0)
(1, 0)
(0, 0)
(0, 0)
(0, 0)
(0, 1)
(0, 1)
(0, 1)
(0, 1)
(0, 1)


In [48]:
foo = np.arange(9, dtype=np.dtype('float64')).reshape(3,3)
for i,x in enumerate(foo):
    print(i,x)
    x *= 1/np.sum(x)
print(foo)

0 [0. 1. 2.]
1 [3. 4. 5.]
2 [6. 7. 8.]
[[0.         0.33333333 0.66666667]
 [0.25       0.33333333 0.41666667]
 [0.28571429 0.33333333 0.38095238]]


In [74]:
def markov_chain(transition_matrix, outputs, rng = None):
    rng = np.random.default_rng(rng)
    n_states, b = transition_matrix.shape
    assert n_states == b == len(outputs)
    transitions = np.zeros((n_states, n_states))
    for i,trans in enumerate(transition_matrix):
        transitions[i] = trans / np.sum(trans)
    state = 0
    while True:
        yield outputs[state]
        state = rng.choice(np.arange(n_states), p = transitions[state])

In [75]:
transitions = np.array([
    [0,1,0,0,0,0,0],
    [0,0,1,0,0,0,0],
    [0,0,0,5,1,1,0],
    [0,0,0,0,0,0,1],
    [0,0,0,0,0,0,1],
    [0,0,0,0,0,0,1],
    [0,1,0,0,0,0,0]
    
])
outputs = [
    '1',
    '2',
    '3',
    '4',
    'y',
    '0',
    '\n'
]

In [76]:
gen = markov_chain(transitions, outputs)
out = []
for i in range(1000):
    out.append(next(gen))
print(' '.join(out))

1 2 3 y 
 2 3 4 
 2 3 4 
 2 3 0 
 2 3 4 
 2 3 4 
 2 3 4 
 2 3 4 
 2 3 4 
 2 3 4 
 2 3 y 
 2 3 4 
 2 3 4 
 2 3 4 
 2 3 4 
 2 3 y 
 2 3 4 
 2 3 4 
 2 3 4 
 2 3 4 
 2 3 y 
 2 3 4 
 2 3 4 
 2 3 0 
 2 3 4 
 2 3 0 
 2 3 4 
 2 3 4 
 2 3 4 
 2 3 4 
 2 3 4 
 2 3 4 
 2 3 y 
 2 3 0 
 2 3 4 
 2 3 4 
 2 3 4 
 2 3 y 
 2 3 0 
 2 3 y 
 2 3 4 
 2 3 0 
 2 3 4 
 2 3 4 
 2 3 4 
 2 3 y 
 2 3 4 
 2 3 0 
 2 3 4 
 2 3 4 
 2 3 4 
 2 3 4 
 2 3 4 
 2 3 4 
 2 3 4 
 2 3 4 
 2 3 0 
 2 3 4 
 2 3 0 
 2 3 4 
 2 3 0 
 2 3 4 
 2 3 4 
 2 3 4 
 2 3 y 
 2 3 y 
 2 3 4 
 2 3 y 
 2 3 y 
 2 3 4 
 2 3 0 
 2 3 4 
 2 3 4 
 2 3 0 
 2 3 y 
 2 3 4 
 2 3 y 
 2 3 y 
 2 3 4 
 2 3 y 
 2 3 4 
 2 3 4 
 2 3 0 
 2 3 y 
 2 3 y 
 2 3 y 
 2 3 4 
 2 3 4 
 2 3 0 
 2 3 y 
 2 3 4 
 2 3 0 
 2 3 4 
 2 3 4 
 2 3 0 
 2 3 0 
 2 3 4 
 2 3 4 
 2 3 4 
 2 3 4 
 2 3 4 
 2 3 4 
 2 3 4 
 2 3 0 
 2 3 4 
 2 3 4 
 2 3 0 
 2 3 4 
 2 3 4 
 2 3 4 
 2 3 0 
 2 3 4 
 2 3 4 
 2 3 4 
 2 3 0 
 2 3 4 
 2 3 y 
 2 3 0 
 2 3 4 
 2 3 4 
 2 3 4 
 2 3 4 
 2 3 0 
 2 3 4 
 2 3 4 

In [77]:
def normalise_transitions(transition_matrix):
    n = len(transition_matrix)
    transitions = np.zeros((n,n))
    for i,trans in enumerate(transition_matrix):
        transitions[i] = trans / np.sum(trans)
    return transitions

In [92]:
def markov_periodic(transition_matrix, outputs, n_iter = -1, state = 0, rng = None):
    rng = np.random.default_rng(rng)
    n_states, b = transition_matrix.shape
    assert n_states == b == len(outputs)
    transitions = normalise_transitions(transition_matrix)
    while n_iter != 0:
        yield outputs[state]
        state = rng.choice(np.arange(n_states), p = transitions[state])
        if state == 0:
            n_iter -= 1

In [85]:
def markov_blocks(block_transitions, blocks, rng = None):
    rng = np.random.default_rng(rng)
    for block in markov_periodic(block_transitions, blocks, rng=rng):
        yield from markov_periodic(**block, rng=rng)

In [93]:
blocks = [
    {'transition_matrix': np.array([
        [0,1,0,0,0],
        [0,0,1,1,0],
        [0,0,0,0,1],
        [0,0,0,0,1],
        [1,0,0,0,0]
    ]), 'outputs': ['a','b','c','d','\n'], 'n_iter': 5},
    {'transition_matrix': np.array([
        [0,1,0,0,0],
        [0,0,1,1,0],
        [0,0,0,0,1],
        [0,0,0,0,1],
        [1,0,0,0,0]
    ]), 'outputs': ['f','g','h','i','\n'], 'n_iter': 8}
]

In [94]:
gen = markov_blocks(np.array([[0,1],[1,0]]), blocks)
out = []
for i in range(1000):
    out.append(next(gen))
print(' '.join(out))

a b c 
 a b c 
 a b c 
 a b c 
 a b d 
 f g h 
 f g i 
 f g i 
 f g h 
 f g i 
 f g i 
 f g h 
 f g i 
 a b c 
 a b c 
 a b d 
 a b c 
 a b c 
 f g i 
 f g i 
 f g i 
 f g i 
 f g i 
 f g h 
 f g i 
 f g i 
 a b d 
 a b d 
 a b d 
 a b c 
 a b d 
 f g h 
 f g i 
 f g i 
 f g i 
 f g h 
 f g h 
 f g i 
 f g i 
 a b d 
 a b c 
 a b c 
 a b d 
 a b d 
 f g h 
 f g h 
 f g h 
 f g h 
 f g i 
 f g i 
 f g i 
 f g i 
 a b c 
 a b d 
 a b c 
 a b d 
 a b c 
 f g i 
 f g i 
 f g h 
 f g i 
 f g i 
 f g h 
 f g h 
 f g i 
 a b d 
 a b d 
 a b d 
 a b d 
 a b c 
 f g h 
 f g h 
 f g i 
 f g i 
 f g h 
 f g h 
 f g h 
 f g i 
 a b c 
 a b d 
 a b c 
 a b c 
 a b d 
 f g i 
 f g i 
 f g i 
 f g i 
 f g h 
 f g h 
 f g i 
 f g h 
 a b d 
 a b c 
 a b c 
 a b c 
 a b c 
 f g i 
 f g i 
 f g i 
 f g h 
 f g i 
 f g h 
 f g h 
 f g i 
 a b c 
 a b c 
 a b d 
 a b d 
 a b c 
 f g h 
 f g i 
 f g h 
 f g i 
 f g i 
 f g i 
 f g i 
 f g i 
 a b d 
 a b d 
 a b d 
 a b c 
 a b d 
 f g h 
 f g h 
 f g i 
 

In [98]:
gen = markov_blocks(np.array([[1]]), [{'transition_matrix': np.array([[5,1],[1,0]]), 'outputs': ['0','1']}])
out = []
for i in range(1000):
    out.append(next(gen))
    if (i+1) % 50 == 0:
        out.append('\n')
print(''.join(out))

00010000100010000000000001000000100000100100100100
00100000000000010000000000001000010000100001000000
01000000100000000101000010101001001000001000010100
00010010000000000001000001001000010010000100000010
00000000100100000100000000000000100010000000100000
00000000000000001000000000000100001000000100000010
01010000000000000000000000001000100000000000010000
10000000000001000000100100001000000000000010000000
00010000001000010000000000000000000010000000000000
00100010100100000100000101000100101010100001000100
00100000001000000000101000000010010001000000000001
00000100010100100010010001000001010000100100000101
00000000000000100001010000000101010001000000000000
00100000001000000000000000000001000001010010000000
00001000001001000100100000000000000010100000100000
00000000100010000001000000000100000000000100001000
00000100000000000000100000000000000000000001000000
00000000000100001000000000000100000000000000000000
01010001010010000001010000000000000000000000000000
0000000010000001001000000000001